name: KBOT-CICD

on:
  push:
    branches:
      - develop

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}
  
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    permissions:
            contents: read
            packages: write

    steps:                          
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run test
        run: make test

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}


      - name: Build&Push
        env:
          APP: "kbot"
          REGISTRY: "${{ env.REGISTRY }}/${{ github.actor }}"
        run: make image push 
      